// Generated by jextract

package jdk.internal.include.sys.sysctl;

import jdk.internal.include.common.Constants$root;
import jdk.internal.include.common.RuntimeHelper;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor sysctlbyname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sysctlbyname$MH = RuntimeHelper.downcallHandle(
        "sysctlbyname",
        constants$0.sysctlbyname$FUNC
    );
}


