// Generated by jextract

package jdk.internal.include.sys.sysctl;

import jdk.internal.include.common.Constants$root;
import jdk.internal.include.common.RuntimeHelper;

import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.*;

final class sysctl_h  {

    private sysctl_h() {}

    /**
     * {@snippet :
     * typedef unsigned long size_t;
     * }
     */
    public static final OfLong size_t = Constants$root.C_LONG_LONG$LAYOUT;
    public static MethodHandle sysctlbyname$MH() {
        return RuntimeHelper.requireNonNull(constants$0.sysctlbyname$MH,"sysctlbyname");
    }

}


