// Generated by jextract

package jdk.internal.include.sys;

public final class __darwin_pthread_rwlock_t extends _opaque_pthread_rwlock_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_rwlock_t() {}
}


