// Generated by jextract

package jdk.internal.include.sys;

import java.lang.foreign.MemorySegment;

final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MemorySegment __DARWIN_SUF_1050$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$1050");
    static final MemorySegment __DARWIN_SUF_EXTSN$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$DARWIN_EXTSN");
    static final MemorySegment __DARWIN_NULL$ADDR = MemorySegment.ofAddress(0L);
}


