// Generated by jextract

package jdk.internal.include.sys;

public final class pthread_mutexattr_t extends _opaque_pthread_mutexattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_mutexattr_t() {}
}


