// Generated by jextract

package jdk.internal.include.sys;

public final class pthread_rwlockattr_t extends _opaque_pthread_rwlockattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_rwlockattr_t() {}
}


