// Generated by jextract

package jdk.internal.include.sys;

public final class pthread_cond_t extends _opaque_pthread_cond_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_cond_t() {}
}


