// Generated by jextract

package jdk.internal.include.sys;

public final class pthread_condattr_t extends _opaque_pthread_condattr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_condattr_t() {}
}


