// Generated by jextract

package jdk.internal.include.sys;

public final class pthread_mutex_t extends _opaque_pthread_mutex_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private pthread_mutex_t() {}
}


