// Generated by jextract

package jdk.internal.include.sys;

public final class sa_endpoints_t extends sa_endpoints {

    // Suppresses default constructor, ensuring non-instantiability.
    private sa_endpoints_t() {}
}


