// Generated by jextract
/*
jextract --source -t jdk.internal.include.sys --dump-includes includes.txt \
  -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/socket.h \
  --include-function sendto \
  --include-function recvfrom \
  --include-function disconnectx \
  --include-function connect \
  --include-macro SAE_ASSOCID_ANY \
  --include-macro SAE_CONNID_ANY \
  --include-typedef socklen_t
 */
package jdk.internal.include.sys;

import jdk.internal.include.common.Constants$root;

import java.lang.foreign.ValueLayout;

final class socket_h  {

    /**
     * {@snippet :
     * #define SAE_ASSOCID_ANY 0
     * }
     */
    static int SAE_ASSOCID_ANY() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define SAE_CONNID_ANY 0
     * }
     */
    static int SAE_CONNID_ANY() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * typedef unsigned int socklen_t;
     * }
     */
    static final ValueLayout.OfInt socklen_t = Constants$root.C_INT$LAYOUT;
    private socket_h() {}
}
