// Generated by jextract

package jdk.internal.include.sys;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class sockproto {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("sp_family"),
        Constants$root.C_SHORT$LAYOUT.withName("sp_protocol")
    ).withName("sockproto");
    public static MemoryLayout $LAYOUT() {
        return sockproto.$struct$LAYOUT;
    }
    static final VarHandle sp_family$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sp_family"));
    public static VarHandle sp_family$VH() {
        return sockproto.sp_family$VH;
    }
    public static short sp_family$get(MemorySegment seg) {
        return (short)sockproto.sp_family$VH.get(seg);
    }
    public static void sp_family$set(MemorySegment seg, short x) {
        sockproto.sp_family$VH.set(seg, x);
    }
    public static short sp_family$get(MemorySegment seg, long index) {
        return (short)sockproto.sp_family$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sp_family$set(MemorySegment seg, long index, short x) {
        sockproto.sp_family$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sp_protocol$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sp_protocol"));
    public static VarHandle sp_protocol$VH() {
        return sockproto.sp_protocol$VH;
    }
    public static short sp_protocol$get(MemorySegment seg) {
        return (short)sockproto.sp_protocol$VH.get(seg);
    }
    public static void sp_protocol$set(MemorySegment seg, short x) {
        sockproto.sp_protocol$VH.set(seg, x);
    }
    public static short sp_protocol$get(MemorySegment seg, long index) {
        return (short)sockproto.sp_protocol$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sp_protocol$set(MemorySegment seg, long index, short x) {
        sockproto.sp_protocol$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


