// Generated by jextract
/*
jextract --source -t jdk.internal.include.netinet --dump-includes includes.txt \
        -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netinet/ \
        /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netinet/in.h \
        --include-struct sockaddr \
        --include-struct sockaddr_in \
        --include-struct sockaddr_in6 \
        --include-macro AF_INET \
        --include-macro AF_INET6 \
        --include-macro AF_UNSPEC*/
package jdk.internal.include.netinet;

final class in_h  {

    /**
     * {@snippet lang = text:
     * #define AF_UNSPEC 0
     * }
     */
    static int AF_UNSPEC() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define AF_INET 2
     * }
     */
    static int AF_INET() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define AF_INET6 30
     * }
     */
    static int AF_INET6() {
        return (int)30L;
    }

    private in_h() {}
}


