// Generated by jextract

package jdk.internal.include.netinet;

final class in_h  {

    /**
     * {@snippet :
     * #define AF_UNSPEC 0
     * }
     */
    static int AF_UNSPEC() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define AF_INET 2
     * }
     */
    static int AF_INET() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define AF_INET6 30
     * }
     */
    static int AF_INET6() {
        return (int)30L;
    }

    private in_h() {}
}


