// Generated by jextract

package jdk.internal.include.netinet;

import jdk.internal.include.common.Constants$root;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
/**
 * {@snippet :
 * struct sockaddr_in6 {
 *     __uint8_t sin6_len;
 *     sa_family_t sin6_family;
 *     in_port_t sin6_port;
 *     __uint32_t sin6_flowinfo;
 *     struct in6_addr sin6_addr;
 *     __uint32_t sin6_scope_id;
 * };
 * }
 */
final class sockaddr_in6 {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("sin6_len"),
        Constants$root.C_CHAR$LAYOUT.withName("sin6_family"),
        Constants$root.C_SHORT$LAYOUT.withName("sin6_port"),
        Constants$root.C_INT$LAYOUT.withName("sin6_flowinfo"),
        MemoryLayout.structLayout(
            MemoryLayout.unionLayout(
                MemoryLayout.sequenceLayout(16, Constants$root.C_CHAR$LAYOUT).withName("__u6_addr8"),
                MemoryLayout.sequenceLayout(8, Constants$root.C_SHORT$LAYOUT).withName("__u6_addr16"),
                MemoryLayout.sequenceLayout(4, Constants$root.C_INT$LAYOUT).withName("__u6_addr32")
            ).withName("__u6_addr")
        ).withName("sin6_addr"),
        Constants$root.C_INT$LAYOUT.withName("sin6_scope_id")
    ).withName("sockaddr_in6");
    static MemoryLayout $LAYOUT() {
        return sockaddr_in6.$struct$LAYOUT;
    }

    /**
     * {@snippet :
     * struct in6_addr {
     *     union  __u6_addr;
     * };
     * }
     */
    static final class in6_addr {

        // Suppresses default constructor, ensuring non-instantiability.
        private in6_addr() {}
        static final StructLayout in6_addr$struct$LAYOUT = MemoryLayout.structLayout(
            MemoryLayout.unionLayout(
                MemoryLayout.sequenceLayout(16, Constants$root.C_CHAR$LAYOUT).withName("__u6_addr8"),
                MemoryLayout.sequenceLayout(8, Constants$root.C_SHORT$LAYOUT).withName("__u6_addr16"),
                MemoryLayout.sequenceLayout(4, Constants$root.C_INT$LAYOUT).withName("__u6_addr32")
            ).withName("__u6_addr")
        ).withName("in6_addr");
        public static MemoryLayout $LAYOUT() {
            return in6_addr.in6_addr$struct$LAYOUT;
        }
        /**
         * {@snippet :
         * union {
         *     __uint8_t __u6_addr8[16];
         *     __uint16_t __u6_addr16[8];
         *     __uint32_t __u6_addr32[4];
         * };
         * }
         */
        static final class __u6_addr {

            // Suppresses default constructor, ensuring non-instantiability.
            private __u6_addr() {}
            static final UnionLayout in6_addr$__u6_addr$union$LAYOUT = MemoryLayout.unionLayout(
                MemoryLayout.sequenceLayout(16, Constants$root.C_CHAR$LAYOUT).withName("__u6_addr8"),
                MemoryLayout.sequenceLayout(8, Constants$root.C_SHORT$LAYOUT).withName("__u6_addr16"),
                MemoryLayout.sequenceLayout(4, Constants$root.C_INT$LAYOUT).withName("__u6_addr32")
            );

            public static MemoryLayout $LAYOUT() {
                return in6_addr$__u6_addr$union$LAYOUT;
            }

        }
    }

    private sockaddr_in6() {}
}
