// Generated by jextract

package jdk.internal.include.netinet;

import jdk.internal.include.common.Constants$root;

import java.lang.foreign.*;
/**
 * {@snippet :
 * struct sockaddr {
 *     __uint8_t sa_len;
 *     sa_family_t sa_family;
 *     char sa_data[14];
 * };
 * }
 */
final class sockaddr {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("sa_len"),
        Constants$root.C_CHAR$LAYOUT.withName("sa_family"),
        MemoryLayout.sequenceLayout(14, Constants$root.C_CHAR$LAYOUT).withName("sa_data")
    ).withName("sockaddr");
    static MemoryLayout $LAYOUT() {
        return sockaddr.$struct$LAYOUT;
    }

    private sockaddr() {}
}


