// Generated by jextract

package jdk.internal.include.netinet;

import jdk.internal.include.common.Constants$root;

import java.lang.foreign.*;

/**
 * {@snippet :
 * struct sockaddr_in {
 *     __uint8_t sin_len;
 *     sa_family_t sin_family;
 *     in_port_t sin_port;
 *     struct in_addr sin_addr;
 *     char sin_zero[8];
 * };
 * }
 */
final class sockaddr_in {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("sin_len"),
        Constants$root.C_CHAR$LAYOUT.withName("sin_family"),
        Constants$root.C_SHORT$LAYOUT.withName("sin_port"),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("s_addr")
        ).withName("sin_addr"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("sin_zero")
    ).withName("sockaddr_in");
    static MemoryLayout $LAYOUT() {
        return sockaddr_in.$struct$LAYOUT;
    }

    static final class in_addr {

        // Suppresses default constructor, ensuring non-instantiability.
        private in_addr() {
        }

        static final StructLayout in_addr$struct$LAYOUT = MemoryLayout.structLayout(
                Constants$root.C_INT$LAYOUT.withName("s_addr")
        ).withName("in_addr");

        static MemoryLayout $LAYOUT() {
            return in_addr$struct$LAYOUT;
        }
    }

    private sockaddr_in() {}
}


