// Generated by jextract

package jdk.internal.sys;

import static java.lang.foreign.ValueLayout.*;

public final class in_h {

    // Suppresses default constructor, ensuring non-instantiability.
    private in_h() {}
    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    public static int AF_INET() {
        return (int)2L;
    }
    public static int AF_INET6() {
        return (int)30L;
    }
}


