// Generated by jextract

package jdk.internal.include;

import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.*;

public final class errno_h {

    // Suppresses default constructor, ensuring non-instantiability.
    private errno_h() {}
/*    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;*/
    public static int __DARWIN_ONLY_64_BIT_INO_T() {
        return (int)0L;
    }
    public static int __DARWIN_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int __DARWIN_ONLY_VERS_1050() {
        return (int)0L;
    }
    public static int __DARWIN_UNIX03() {
        return (int)1L;
    }
    public static int __DARWIN_64_BIT_INO_T() {
        return (int)1L;
    }
    public static int __DARWIN_VERS_1050() {
        return (int)1L;
    }
    public static int __DARWIN_NON_CANCELABLE() {
        return (int)0L;
    }
    public static int __STDC_WANT_LIB_EXT1__() {
        return (int)1L;
    }
    public static int __DARWIN_NO_LONG_LONG() {
        return (int)0L;
    }
    public static int _DARWIN_FEATURE_64_BIT_INODE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_UNIX_CONFORMANCE() {
        return (int)3L;
    }
    public static int __has_ptrcheck() {
        return (int)0L;
    }
    public static int EPERM() {
        return (int)1L;
    }
    public static int ENOENT() {
        return (int)2L;
    }
    public static int ESRCH() {
        return (int)3L;
    }
    public static int EINTR() {
        return (int)4L;
    }
    public static int EIO() {
        return (int)5L;
    }
    public static int ENXIO() {
        return (int)6L;
    }
    public static int E2BIG() {
        return (int)7L;
    }
    public static int ENOEXEC() {
        return (int)8L;
    }
    public static int EBADF() {
        return (int)9L;
    }
    public static int ECHILD() {
        return (int)10L;
    }
    public static int EDEADLK() {
        return (int)11L;
    }
    public static int ENOMEM() {
        return (int)12L;
    }
    public static int EACCES() {
        return (int)13L;
    }
    public static int EFAULT() {
        return (int)14L;
    }
    public static int ENOTBLK() {
        return (int)15L;
    }
    public static int EBUSY() {
        return (int)16L;
    }
    public static int EEXIST() {
        return (int)17L;
    }
    public static int EXDEV() {
        return (int)18L;
    }
    public static int ENODEV() {
        return (int)19L;
    }
    public static int ENOTDIR() {
        return (int)20L;
    }
    public static int EISDIR() {
        return (int)21L;
    }
    public static int EINVAL() {
        return (int)22L;
    }
    public static int ENFILE() {
        return (int)23L;
    }
    public static int EMFILE() {
        return (int)24L;
    }
    public static int ENOTTY() {
        return (int)25L;
    }
    public static int ETXTBSY() {
        return (int)26L;
    }
    public static int EFBIG() {
        return (int)27L;
    }
    public static int ENOSPC() {
        return (int)28L;
    }
    public static int ESPIPE() {
        return (int)29L;
    }
    public static int EROFS() {
        return (int)30L;
    }
    public static int EMLINK() {
        return (int)31L;
    }
    public static int EPIPE() {
        return (int)32L;
    }
    public static int EDOM() {
        return (int)33L;
    }
    public static int ERANGE() {
        return (int)34L;
    }
    public static int EAGAIN() {
        return (int)35L;
    }
    public static int EINPROGRESS() {
        return (int)36L;
    }
    public static int EALREADY() {
        return (int)37L;
    }
    public static int ENOTSOCK() {
        return (int)38L;
    }
    public static int EDESTADDRREQ() {
        return (int)39L;
    }
    public static int EMSGSIZE() {
        return (int)40L;
    }
    public static int EPROTOTYPE() {
        return (int)41L;
    }
    public static int ENOPROTOOPT() {
        return (int)42L;
    }
    public static int EPROTONOSUPPORT() {
        return (int)43L;
    }
    public static int ESOCKTNOSUPPORT() {
        return (int)44L;
    }
    public static int ENOTSUP() {
        return (int)45L;
    }
    public static int EPFNOSUPPORT() {
        return (int)46L;
    }
    public static int EAFNOSUPPORT() {
        return (int)47L;
    }
    public static int EADDRINUSE() {
        return (int)48L;
    }
    public static int EADDRNOTAVAIL() {
        return (int)49L;
    }
    public static int ENETDOWN() {
        return (int)50L;
    }
    public static int ENETUNREACH() {
        return (int)51L;
    }
    public static int ENETRESET() {
        return (int)52L;
    }
    public static int ECONNABORTED() {
        return (int)53L;
    }
    public static int ECONNRESET() {
        return (int)54L;
    }
    public static int ENOBUFS() {
        return (int)55L;
    }
    public static int EISCONN() {
        return (int)56L;
    }
    public static int ENOTCONN() {
        return (int)57L;
    }
    public static int ESHUTDOWN() {
        return (int)58L;
    }
    public static int ETOOMANYREFS() {
        return (int)59L;
    }
    public static int ETIMEDOUT() {
        return (int)60L;
    }
    public static int ECONNREFUSED() {
        return (int)61L;
    }
    public static int ELOOP() {
        return (int)62L;
    }
    public static int ENAMETOOLONG() {
        return (int)63L;
    }
    public static int EHOSTDOWN() {
        return (int)64L;
    }
    public static int EHOSTUNREACH() {
        return (int)65L;
    }
    public static int ENOTEMPTY() {
        return (int)66L;
    }
    public static int EPROCLIM() {
        return (int)67L;
    }
    public static int EUSERS() {
        return (int)68L;
    }
    public static int EDQUOT() {
        return (int)69L;
    }
    public static int ESTALE() {
        return (int)70L;
    }
    public static int EREMOTE() {
        return (int)71L;
    }
    public static int EBADRPC() {
        return (int)72L;
    }
    public static int ERPCMISMATCH() {
        return (int)73L;
    }
    public static int EPROGUNAVAIL() {
        return (int)74L;
    }
    public static int EPROGMISMATCH() {
        return (int)75L;
    }
    public static int EPROCUNAVAIL() {
        return (int)76L;
    }
    public static int ENOLCK() {
        return (int)77L;
    }
    public static int ENOSYS() {
        return (int)78L;
    }
    public static int EFTYPE() {
        return (int)79L;
    }
    public static int EAUTH() {
        return (int)80L;
    }
    public static int ENEEDAUTH() {
        return (int)81L;
    }
    public static int EPWROFF() {
        return (int)82L;
    }
    public static int EDEVERR() {
        return (int)83L;
    }
    public static int EOVERFLOW() {
        return (int)84L;
    }
    public static int EBADEXEC() {
        return (int)85L;
    }
    public static int EBADARCH() {
        return (int)86L;
    }
    public static int ESHLIBVERS() {
        return (int)87L;
    }
    public static int EBADMACHO() {
        return (int)88L;
    }
    public static int ECANCELED() {
        return (int)89L;
    }
    public static int EIDRM() {
        return (int)90L;
    }
    public static int ENOMSG() {
        return (int)91L;
    }
    public static int EILSEQ() {
        return (int)92L;
    }
    public static int ENOATTR() {
        return (int)93L;
    }
    public static int EBADMSG() {
        return (int)94L;
    }
    public static int EMULTIHOP() {
        return (int)95L;
    }
    public static int ENODATA() {
        return (int)96L;
    }
    public static int ENOLINK() {
        return (int)97L;
    }
    public static int ENOSR() {
        return (int)98L;
    }
    public static int ENOSTR() {
        return (int)99L;
    }
    public static int EPROTO() {
        return (int)100L;
    }
    public static int ETIME() {
        return (int)101L;
    }
    public static int EOPNOTSUPP() {
        return (int)102L;
    }
    public static int ENOPOLICY() {
        return (int)103L;
    }
    public static int ENOTRECOVERABLE() {
        return (int)104L;
    }
    public static int EOWNERDEAD() {
        return (int)105L;
    }
    public static int EQFULL() {
        return (int)106L;
    }
    public static int ELAST() {
        return (int)106L;
    }
/*    public static final OfInt errno_t = Constants$root.C_INT$LAYOUT;
    public static MethodHandle __error$MH() {
        return RuntimeHelper.requireNonNull(constants$0.__error$MH,"__error");
    }
    public static MemorySegment __error() {
        var mh$ = __error$MH();
        try {
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MemorySegment __DARWIN_SUF_64_BIT_INO_T() {
        return constants$0.__DARWIN_SUF_64_BIT_INO_T$SEGMENT;
    }
    public static MemorySegment __DARWIN_SUF_1050() {
        return constants$0.__DARWIN_SUF_1050$SEGMENT;
    }
    public static MemorySegment __DARWIN_SUF_EXTSN() {
        return constants$0.__DARWIN_SUF_EXTSN$SEGMENT;
    }*/
    public static long __DARWIN_C_ANSI() {
        return 4096L;
    }
    public static long __DARWIN_C_FULL() {
        return 900000L;
    }
    public static long __DARWIN_C_LEVEL() {
        return 900000L;
    }
    public static int EWOULDBLOCK() {
        return (int)35L;
    }
}


