// Generated by jextract

package jdk.internal.include;

import jdk.internal.include.common.Constants$root;
import jdk.internal.include.common.RuntimeHelper;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;

final class errno_h  {

    /**
     * {@snippet :
     * #define __DARWIN_ONLY_64_BIT_INO_T 1
     * }
     */
    static int __DARWIN_ONLY_64_BIT_INO_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_ONLY_UNIX_CONFORMANCE 1
     * }
     */
    static int __DARWIN_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_ONLY_VERS_1050 1
     * }
     */
    static int __DARWIN_ONLY_VERS_1050() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_UNIX03 1
     * }
     */
    static int __DARWIN_UNIX03() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_64_BIT_INO_T 1
     * }
     */
    static int __DARWIN_64_BIT_INO_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_VERS_1050 1
     * }
     */
    static int __DARWIN_VERS_1050() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_NON_CANCELABLE 0
     * }
     */
    static int __DARWIN_NON_CANCELABLE() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __STDC_WANT_LIB_EXT1__ 1
     * }
     */
    static int __STDC_WANT_LIB_EXT1__() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_NO_LONG_LONG 0
     * }
     */
    static int __DARWIN_NO_LONG_LONG() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _DARWIN_FEATURE_64_BIT_INODE 1
     * }
     */
    static int _DARWIN_FEATURE_64_BIT_INODE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DARWIN_FEATURE_ONLY_64_BIT_INODE 1
     * }
     */
    static int _DARWIN_FEATURE_ONLY_64_BIT_INODE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DARWIN_FEATURE_ONLY_VERS_1050 1
     * }
     */
    static int _DARWIN_FEATURE_ONLY_VERS_1050() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE 1
     * }
     */
    static int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DARWIN_FEATURE_UNIX_CONFORMANCE 3
     * }
     */
    static int _DARWIN_FEATURE_UNIX_CONFORMANCE() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define __has_ptrcheck 0
     * }
     */
    static int __has_ptrcheck() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define EPERM 1
     * }
     */
    static int EPERM() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define ENOENT 2
     * }
     */
    static int ENOENT() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define ESRCH 3
     * }
     */
    static int ESRCH() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * #define EINTR 4
     * }
     */
    static int EINTR() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * #define EIO 5
     * }
     */
    static int EIO() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * #define ENXIO 6
     * }
     */
    static int ENXIO() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define E2BIG 7
     * }
     */
    static int E2BIG() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * #define ENOEXEC 8
     * }
     */
    static int ENOEXEC() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define EBADF 9
     * }
     */
    static int EBADF() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * #define ECHILD 10
     * }
     */
    static int ECHILD() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * #define EDEADLK 11
     * }
     */
    static int EDEADLK() {
        return (int)11L;
    }
    /**
     * {@snippet :
     * #define ENOMEM 12
     * }
     */
    static int ENOMEM() {
        return (int)12L;
    }
    /**
     * {@snippet :
     * #define EACCES 13
     * }
     */
    static int EACCES() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * #define EFAULT 14
     * }
     */
    static int EFAULT() {
        return (int)14L;
    }
    /**
     * {@snippet :
     * #define ENOTBLK 15
     * }
     */
    static int ENOTBLK() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * #define EBUSY 16
     * }
     */
    static int EBUSY() {
        return (int)16L;
    }
    /**
     * {@snippet :
     * #define EEXIST 17
     * }
     */
    static int EEXIST() {
        return (int)17L;
    }
    /**
     * {@snippet :
     * #define EXDEV 18
     * }
     */
    static int EXDEV() {
        return (int)18L;
    }
    /**
     * {@snippet :
     * #define ENODEV 19
     * }
     */
    static int ENODEV() {
        return (int)19L;
    }
    /**
     * {@snippet :
     * #define ENOTDIR 20
     * }
     */
    static int ENOTDIR() {
        return (int)20L;
    }
    /**
     * {@snippet :
     * #define EISDIR 21
     * }
     */
    static int EISDIR() {
        return (int)21L;
    }
    /**
     * {@snippet :
     * #define EINVAL 22
     * }
     */
    static int EINVAL() {
        return (int)22L;
    }
    /**
     * {@snippet :
     * #define ENFILE 23
     * }
     */
    static int ENFILE() {
        return (int)23L;
    }
    /**
     * {@snippet :
     * #define EMFILE 24
     * }
     */
    static int EMFILE() {
        return (int)24L;
    }
    /**
     * {@snippet :
     * #define ENOTTY 25
     * }
     */
    static int ENOTTY() {
        return (int)25L;
    }
    /**
     * {@snippet :
     * #define ETXTBSY 26
     * }
     */
    static int ETXTBSY() {
        return (int)26L;
    }
    /**
     * {@snippet :
     * #define EFBIG 27
     * }
     */
    static int EFBIG() {
        return (int)27L;
    }
    /**
     * {@snippet :
     * #define ENOSPC 28
     * }
     */
    static int ENOSPC() {
        return (int)28L;
    }
    /**
     * {@snippet :
     * #define ESPIPE 29
     * }
     */
    static int ESPIPE() {
        return (int)29L;
    }
    /**
     * {@snippet :
     * #define EROFS 30
     * }
     */
    static int EROFS() {
        return (int)30L;
    }
    /**
     * {@snippet :
     * #define EMLINK 31
     * }
     */
    static int EMLINK() {
        return (int)31L;
    }
    /**
     * {@snippet :
     * #define EPIPE 32
     * }
     */
    static int EPIPE() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * #define EDOM 33
     * }
     */
    static int EDOM() {
        return (int)33L;
    }
    /**
     * {@snippet :
     * #define ERANGE 34
     * }
     */
    static int ERANGE() {
        return (int)34L;
    }
    /**
     * {@snippet :
     * #define EAGAIN 35
     * }
     */
    static int EAGAIN() {
        return (int)35L;
    }
    /**
     * {@snippet :
     * #define EINPROGRESS 36
     * }
     */
    static int EINPROGRESS() {
        return (int)36L;
    }
    /**
     * {@snippet :
     * #define EALREADY 37
     * }
     */
    static int EALREADY() {
        return (int)37L;
    }
    /**
     * {@snippet :
     * #define ENOTSOCK 38
     * }
     */
    static int ENOTSOCK() {
        return (int)38L;
    }
    /**
     * {@snippet :
     * #define EDESTADDRREQ 39
     * }
     */
    static int EDESTADDRREQ() {
        return (int)39L;
    }
    /**
     * {@snippet :
     * #define EMSGSIZE 40
     * }
     */
    static int EMSGSIZE() {
        return (int)40L;
    }
    /**
     * {@snippet :
     * #define EPROTOTYPE 41
     * }
     */
    static int EPROTOTYPE() {
        return (int)41L;
    }
    /**
     * {@snippet :
     * #define ENOPROTOOPT 42
     * }
     */
    static int ENOPROTOOPT() {
        return (int)42L;
    }
    /**
     * {@snippet :
     * #define EPROTONOSUPPORT 43
     * }
     */
    static int EPROTONOSUPPORT() {
        return (int)43L;
    }
    /**
     * {@snippet :
     * #define ESOCKTNOSUPPORT 44
     * }
     */
    static int ESOCKTNOSUPPORT() {
        return (int)44L;
    }
    /**
     * {@snippet :
     * #define ENOTSUP 45
     * }
     */
    static int ENOTSUP() {
        return (int)45L;
    }
    /**
     * {@snippet :
     * #define EPFNOSUPPORT 46
     * }
     */
    static int EPFNOSUPPORT() {
        return (int)46L;
    }
    /**
     * {@snippet :
     * #define EAFNOSUPPORT 47
     * }
     */
    static int EAFNOSUPPORT() {
        return (int)47L;
    }
    /**
     * {@snippet :
     * #define EADDRINUSE 48
     * }
     */
    static int EADDRINUSE() {
        return (int)48L;
    }
    /**
     * {@snippet :
     * #define EADDRNOTAVAIL 49
     * }
     */
    static int EADDRNOTAVAIL() {
        return (int)49L;
    }
    /**
     * {@snippet :
     * #define ENETDOWN 50
     * }
     */
    static int ENETDOWN() {
        return (int)50L;
    }
    /**
     * {@snippet :
     * #define ENETUNREACH 51
     * }
     */
    static int ENETUNREACH() {
        return (int)51L;
    }
    /**
     * {@snippet :
     * #define ENETRESET 52
     * }
     */
    static int ENETRESET() {
        return (int)52L;
    }
    /**
     * {@snippet :
     * #define ECONNABORTED 53
     * }
     */
    static int ECONNABORTED() {
        return (int)53L;
    }
    /**
     * {@snippet :
     * #define ECONNRESET 54
     * }
     */
    static int ECONNRESET() {
        return (int)54L;
    }
    /**
     * {@snippet :
     * #define ENOBUFS 55
     * }
     */
    static int ENOBUFS() {
        return (int)55L;
    }
    /**
     * {@snippet :
     * #define EISCONN 56
     * }
     */
    static int EISCONN() {
        return (int)56L;
    }
    /**
     * {@snippet :
     * #define ENOTCONN 57
     * }
     */
    static int ENOTCONN() {
        return (int)57L;
    }
    /**
     * {@snippet :
     * #define ESHUTDOWN 58
     * }
     */
    static int ESHUTDOWN() {
        return (int)58L;
    }
    /**
     * {@snippet :
     * #define ETOOMANYREFS 59
     * }
     */
    static int ETOOMANYREFS() {
        return (int)59L;
    }
    /**
     * {@snippet :
     * #define ETIMEDOUT 60
     * }
     */
    static int ETIMEDOUT() {
        return (int)60L;
    }
    /**
     * {@snippet :
     * #define ECONNREFUSED 61
     * }
     */
    static int ECONNREFUSED() {
        return (int)61L;
    }
    /**
     * {@snippet :
     * #define ELOOP 62
     * }
     */
    static int ELOOP() {
        return (int)62L;
    }
    /**
     * {@snippet :
     * #define ENAMETOOLONG 63
     * }
     */
    static int ENAMETOOLONG() {
        return (int)63L;
    }
    /**
     * {@snippet :
     * #define EHOSTDOWN 64
     * }
     */
    static int EHOSTDOWN() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define EHOSTUNREACH 65
     * }
     */
    static int EHOSTUNREACH() {
        return (int)65L;
    }
    /**
     * {@snippet :
     * #define ENOTEMPTY 66
     * }
     */
    static int ENOTEMPTY() {
        return (int)66L;
    }
    /**
     * {@snippet :
     * #define EPROCLIM 67
     * }
     */
    static int EPROCLIM() {
        return (int)67L;
    }
    /**
     * {@snippet :
     * #define EUSERS 68
     * }
     */
    static int EUSERS() {
        return (int)68L;
    }
    /**
     * {@snippet :
     * #define EDQUOT 69
     * }
     */
    static int EDQUOT() {
        return (int)69L;
    }
    /**
     * {@snippet :
     * #define ESTALE 70
     * }
     */
    static int ESTALE() {
        return (int)70L;
    }
    /**
     * {@snippet :
     * #define EREMOTE 71
     * }
     */
    static int EREMOTE() {
        return (int)71L;
    }
    /**
     * {@snippet :
     * #define EBADRPC 72
     * }
     */
    static int EBADRPC() {
        return (int)72L;
    }
    /**
     * {@snippet :
     * #define ERPCMISMATCH 73
     * }
     */
    static int ERPCMISMATCH() {
        return (int)73L;
    }
    /**
     * {@snippet :
     * #define EPROGUNAVAIL 74
     * }
     */
    static int EPROGUNAVAIL() {
        return (int)74L;
    }
    /**
     * {@snippet :
     * #define EPROGMISMATCH 75
     * }
     */
    static int EPROGMISMATCH() {
        return (int)75L;
    }
    /**
     * {@snippet :
     * #define EPROCUNAVAIL 76
     * }
     */
    static int EPROCUNAVAIL() {
        return (int)76L;
    }
    /**
     * {@snippet :
     * #define ENOLCK 77
     * }
     */
    static int ENOLCK() {
        return (int)77L;
    }
    /**
     * {@snippet :
     * #define ENOSYS 78
     * }
     */
    static int ENOSYS() {
        return (int)78L;
    }
    /**
     * {@snippet :
     * #define EFTYPE 79
     * }
     */
    static int EFTYPE() {
        return (int)79L;
    }
    /**
     * {@snippet :
     * #define EAUTH 80
     * }
     */
    static int EAUTH() {
        return (int)80L;
    }
    /**
     * {@snippet :
     * #define ENEEDAUTH 81
     * }
     */
    static int ENEEDAUTH() {
        return (int)81L;
    }
    /**
     * {@snippet :
     * #define EPWROFF 82
     * }
     */
    static int EPWROFF() {
        return (int)82L;
    }
    /**
     * {@snippet :
     * #define EDEVERR 83
     * }
     */
    static int EDEVERR() {
        return (int)83L;
    }
    /**
     * {@snippet :
     * #define EOVERFLOW 84
     * }
     */
    static int EOVERFLOW() {
        return (int)84L;
    }
    /**
     * {@snippet :
     * #define EBADEXEC 85
     * }
     */
    static int EBADEXEC() {
        return (int)85L;
    }
    /**
     * {@snippet :
     * #define EBADARCH 86
     * }
     */
    static int EBADARCH() {
        return (int)86L;
    }
    /**
     * {@snippet :
     * #define ESHLIBVERS 87
     * }
     */
    static int ESHLIBVERS() {
        return (int)87L;
    }
    /**
     * {@snippet :
     * #define EBADMACHO 88
     * }
     */
    static int EBADMACHO() {
        return (int)88L;
    }
    /**
     * {@snippet :
     * #define ECANCELED 89
     * }
     */
    static int ECANCELED() {
        return (int)89L;
    }
    /**
     * {@snippet :
     * #define EIDRM 90
     * }
     */
    static int EIDRM() {
        return (int)90L;
    }
    /**
     * {@snippet :
     * #define ENOMSG 91
     * }
     */
    static int ENOMSG() {
        return (int)91L;
    }
    /**
     * {@snippet :
     * #define EILSEQ 92
     * }
     */
    static int EILSEQ() {
        return (int)92L;
    }
    /**
     * {@snippet :
     * #define ENOATTR 93
     * }
     */
    static int ENOATTR() {
        return (int)93L;
    }
    /**
     * {@snippet :
     * #define EBADMSG 94
     * }
     */
    static int EBADMSG() {
        return (int)94L;
    }
    /**
     * {@snippet :
     * #define EMULTIHOP 95
     * }
     */
    static int EMULTIHOP() {
        return (int)95L;
    }
    /**
     * {@snippet :
     * #define ENODATA 96
     * }
     */
    static int ENODATA() {
        return (int)96L;
    }
    /**
     * {@snippet :
     * #define ENOLINK 97
     * }
     */
    static int ENOLINK() {
        return (int)97L;
    }
    /**
     * {@snippet :
     * #define ENOSR 98
     * }
     */
    static int ENOSR() {
        return (int)98L;
    }
    /**
     * {@snippet :
     * #define ENOSTR 99
     * }
     */
    static int ENOSTR() {
        return (int)99L;
    }
    /**
     * {@snippet :
     * #define EPROTO 100
     * }
     */
    static int EPROTO() {
        return (int)100L;
    }
    /**
     * {@snippet :
     * #define ETIME 101
     * }
     */
    static int ETIME() {
        return (int)101L;
    }
    /**
     * {@snippet :
     * #define EOPNOTSUPP 102
     * }
     */
    static int EOPNOTSUPP() {
        return (int)102L;
    }
    /**
     * {@snippet :
     * #define ENOPOLICY 103
     * }
     */
    static int ENOPOLICY() {
        return (int)103L;
    }
    /**
     * {@snippet :
     * #define ENOTRECOVERABLE 104
     * }
     */
    static int ENOTRECOVERABLE() {
        return (int)104L;
    }
    /**
     * {@snippet :
     * #define EOWNERDEAD 105
     * }
     */
    static int EOWNERDEAD() {
        return (int)105L;
    }
    /**
     * {@snippet :
     * #define EQFULL 106
     * }
     */
    static int EQFULL() {
        return (int)106L;
    }
    /**
     * {@snippet :
     * #define ELAST 106
     * }
     */
    static int ELAST() {
        return (int)106L;
    }
    /**
     * {@snippet :
     * typedef int errno_t;
     * }
     */
    static final ValueLayout.OfInt errno_t = Constants$root.C_INT$LAYOUT;
    static MethodHandle __error$MH() {
        return RuntimeHelper.requireNonNull(constants$0.__error$MH,"__error");
    }
    /**
     * {@snippet :
     * int* __error();
     * }
     */
    static MemorySegment __error() {
        var mh$ = __error$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * #define __DARWIN_SUF_EXTSN "$DARWIN_EXTSN"
     * }
     */
    static MemorySegment __DARWIN_SUF_EXTSN() {
        return constants$0.__DARWIN_SUF_EXTSN$SEGMENT;
    }
    /**
     * {@snippet :
     * #define __DARWIN_C_ANSI 4096
     * }
     */
    static long __DARWIN_C_ANSI() {
        return 4096L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_C_FULL 900000
     * }
     */
    static long __DARWIN_C_FULL() {
        return 900000L;
    }
    /**
     * {@snippet :
     * #define __DARWIN_C_LEVEL 900000
     * }
     */
    static long __DARWIN_C_LEVEL() {
        return 900000L;
    }
    /**
     * {@snippet :
     * #define EWOULDBLOCK 35
     * }
     */
    static int EWOULDBLOCK() {
        return (int)35L;
    }
}


