// Generated by jextract

package jdk.internal.include.netinet;

public final class InH {

    public static int AF_UNSPEC() {
        return in_h.AF_UNSPEC();
    }
    public static int AF_INET() {
        return in_h.AF_INET();
    }
    public static int AF_INET6() {
        return in_h.AF_INET6();
    }

    private InH() {}
}


