// Generated by jextract

package jdk.internal.include.common;

import static java.lang.foreign.ValueLayout.*;
public final class Constants$root {

    // Suppresses default constructor, ensuring non-instantiability.
    private Constants$root() {}
    public static final OfBoolean C_BOOL$LAYOUT = JAVA_BOOLEAN;
    public static final OfByte C_CHAR$LAYOUT = JAVA_BYTE;
    public static final OfShort C_SHORT$LAYOUT = JAVA_SHORT;
    public static final OfInt C_INT$LAYOUT = JAVA_INT;
    public static final OfLong C_LONG$LAYOUT = JAVA_LONG;
    public static final OfLong C_LONG_LONG$LAYOUT = JAVA_LONG;
    public static final OfFloat C_FLOAT$LAYOUT = JAVA_FLOAT;
    public static final OfDouble C_DOUBLE$LAYOUT = JAVA_DOUBLE;
    public static final OfAddress C_POINTER$LAYOUT = ADDRESS.withBitAlignment(64).asUnbounded();
}


